### ISSUE TITLE
History after search is still on working after pr #1058

### ISSUE THREAD

**Issue by matthieubessol** [searchkit/searchkit#1063]
## The problem

After making a search and going to a page that does not use **withSearchkitRouting**, the url change but not the page.

## Environment

* Searchkit version (or git revision) that exhibits the issue: 3.0.0-canary.47
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: 14.15-alpine3.12
* Typescript version:
* Apollo version: 3.3.20
* Next.js version: 11.1.3
* ElasticSearch/OpenSearch version:

## Details

After typing the search and getting the result, if we click on a page with next/link that does not use **withSearchkitRouting** and going back to previous page, the url is changing but not the page. The pull request https://github.com/searchkit/searchkit/pull/1058 did not helped to fixed it.

## Code To Reproduce Issue

We can reproduce it on the demo of the ssr page. https://demo.searchkit.co/ssr-example
Steps:
1 - Do a search "dark knight" for example and type enter
2 - Click on "Link to a new page"
3 - Go back

**Comment by joemcelroy** [comment]
thanks! Yeh looks like for this scenario it isn't working. Will investigate when I have time, likely the route change listener isn't getting fired or not re-rendering

**Comment by joemcelroy** [comment]
So having a go at figuring out the issue here and I believe its caused by utilizing the browser history APIs directly where next loses awareness of page transitions. I managed to fix it by replacing the API calls to browser with next/router's equivalents and worked as expected. 

With the SearchkitRouting HOC being so coupled to NextJS anyway, I will replace the browser history APIs invocations with next/routers ones. How I solved it was writing a new History class for nextjs. 

Happy to accept a PR for this otherwise I will get on with it when I can.

The workaround for now is to use a native a element rather than the nextjs Link so its not a client side page transition.
