### ISSUE TITLE
Implementing 3 searchboxes using SearchKit

### ISSUE THREAD

**Issue by anuj-sali** [searchkit/searchkit#1248]
## The problem
 I want to implement a webpage having two panels. On Left panel, I want three searchboxes having different search settings. On Right Panel, I want to show results of these 3 searchboxes. I'm using elasticsearch as my search engine.

## Environment

* Searchkit version : 4.4.3
* Node.js version: 18.14.1
* ElasticSearch/OpenSearch version: 8.6.2 [local setup]

## Details
I want to implement a webpage having two panels. On Left panel, I want three searchboxes having different search settings. On Right Panel, I want to show results of these 4 searchboxes. I'm using elasticsearch as my search engine.
I tried to use 4 searchClients for these searchboxes, but issue is the right panel should also come inside tag of InstantSearch <>. 

##Meta info of the sample code:
Right now , I have just implemented InstantSearch tag for 1 searchbox. This I have to accomplish for other 2 searchboxes as well.

##Sample Code of Issue:
<InstantSearch indexName="index_1" searchClient={searchClient} >
        <EuiPageHeader
            pageTitle={<span className="fs-1" style={{"marginRight": "20px"}} >Search:</span>}
            iconType="searchProfilerApp"
            alignItems={'center'}
        />
        <EuiFlexGroup>
            <EuiFlexItem grow={4}>
                <EuiPanel>       
                    <EuiFormRow label="Free Text Search" helpText="Search in all available columns">
                   <SearchBox />
                    </EuiFormRow>

                    <EuiFormRow label="Name">
                  //      <SearchBox />
                    </EuiFormRow>
                    <EuiFormRow label="Compromised Data">
                //         <SearchBox />
                    </EuiFormRow>       
                </EuiPanel>
            </EuiFlexItem>
            <EuiFlexItem grow={8}>
                <EuiPanel className='eui-yScroll' style={{maxHeight:'455px'}}>
                <Hits hitComponent={hitView}/>
                </EuiPanel>
            </EuiFlexItem>
        </EuiFlexGroup>
</InstantSearch>

**Comment by joemcelroy** [comment]
Just an update: 

Im committing an example of this + couple of code changes to make this easier. Hope to share tomorrow!

Joe

**Comment by joemcelroy** [comment]
Provided an example of how you can add separate filter inputs targeting a field. 

See example: 
1. Add a filter attribute with the field. Also note that the field is a standard field and we have specified a custom FilterQuery. This is so filters applying to this filter will use `match` rather than the default `term`. See [code example](https://github.com/searchkit/searchkit/blob/main/examples/with-ui-nextjs-react/pages/api/search.ts#L30-L35)
2. Add a new component on frontend to use this filter. Its shown as a normal input field. See [code example](https://github.com/searchkit/searchkit/blob/main/examples/with-ui-nextjs-react/pages/index.tsx#L22-L63) 

This works on v4.5. You can see it in action here, labelled as "writers"

https://codesandbox.io/s/github/searchkit/searchkit/tree/main/examples/with-ui-nextjs-react?file=/package.json
