### ISSUE TITLE
Add support for NOT operator in Refinement Lists.

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#150]
What it says on the tin. AND/OR are useful, but NOT is even more so.

**Comment by ssetem** [comment]
@PAK90 could you give a couple of example usecases for this? just to help us understand the feature

**Comment by GregoryPotdevin** [comment]
RefinementListFilter only supports AND/OR. He's asking for NOT :)

**Comment by ssetem** [comment]
yeh I know that:) I wanted to see concrete usecase, and whether its not red + blue or not red or not blue, stuff like this :D

**Comment by ssetem** [comment]
the not filter + multiple searchboxes, sounds like a potential query builder to me :D

**Comment by PAK90** [comment]
Yep, sorry, should've done an example. For my data, docs can have any combination of 5 colours or be colourless. Right now I have a refinement list that lists these 6 options, and so I can see all Blue docs, all Red docs, all Blue and Red docs, all Blue and Red and White docs etc. I'd like a NOT option so that I could see all Red docs with ONLY red in them (so the other colours would be selected as NOT), or Blue and Red NOT white, etc. Hope that makes sense.

@ssetem yeah, a query builder is kind of what I'm aiming for in the long run.

**Comment by GregoryPotdevin** [comment]
I got my head around what the NOT RefinementList should look like and now it seems clear why you want it... Compared to the AND/OR filters, the idea would be to display like a normal RefinementList but with all items checked by default, and toggling the items would add them to the state as NOT keys and uncheck them visually.
For some facets it can actually make more sense for the end user : by default, everything is selected, and you want to REMOVE some values. In @PAK90's case, I can see how he could like to have all colors checked by default, and have the user uncheck colors that should never come up in the search. The difference with the AND/OR filter is that if you have only `red` and `black` checked, you'll only get cards with pure red, pure black, or red+black, and you can't get `red` + `other color` (plus an edge case I'll talk about later on). That would work really well with the new Toggle component.

It should be pretty easy to build :
- **accessor** => close to 0 code, the toggle logic is the same, it just needs to be a NOT operator
- **ui** => shouldn't have any change to do
- **RefinementListFilter** => that's the tricky one, we'll need to reverse the selected list : take all keys from the buckets and remove from those keys the selected ones, so the UI displays the inverted state (probably easier than pushing the invert logic to all UI components)

My main issue with this is that mixing NOT filters with other filters in a single search UI could be misleading for the end user. Having 2 elements ticked in the NOT filter will look just like having 2 elements ticked in the AND/OR filter, but the result will be very different (for array fields), it acts kind of like an OR but not quite : 
If A and B are visually ticked, you'll get results with 
`(arr == [A, B]) OR (arr == [A]) OR (arr == [B]) OR (arr == [])`
That last one can be surprising depending on the context. If in your data the field can never be empty it's not a problem.

The other display possibility which doesn't have this shortcoming and is even easier to implement is by having a big red cross next to the selected NOT items instead of a checkbox. It makes it more explicit that it's a NOT but I think end users will have a harder timing wrapping their head around it.

In all cases, adding NOT to the accessor isn't a problem and doesn't add any extra logic or edge cases. That could allow developers to play with it and see if anything interesting comes out of it (before adding the corresponding RefinementListFilter/UI behaviors).

**Comment by xinghengwang** [comment]
The having red crosses next to the checkboxes is a great idea, is there any follow up on this?

**Comment by PAK90** [comment]
@xinghengwang I managed to create a modified filter called 'Only', which basically sent down 'not' requests for all other categories inside a refinement filter apart from the ones selected, but it's not the same as a 'Not', and it's impractical for filters with large (> 10) numbers of categories. I'm hoping that an individual 'not' for each filter category is something that gets released officially. If not, I have vague ideas on how to attempt it, but it'd probably take a while to implement.

**Comment by timtutt** [comment]
This solution might be over complicated. Wouldn't it be pretty straight forward and intuitive to a user to have a +/- option that just adds a bool filter with must or must_not depending on the option chosen. You can add it to the refinements list as "(Not) Red"  for display-ability, but you also don't have to have all the other elements ticked... So the user can then select all documents that are Not red without having to explicitly include docs. 

Concept image:

![image](https://cloud.githubusercontent.com/assets/1517492/24086309/a9a3929c-0ce3-11e7-970f-895e76132616.png)

**Comment by samdash** [comment]
Any update on this ?

**Comment by stereosteve** [comment]
Google Flights airline selector has a nice UI for this

<img width="290" alt="screen shot 2017-11-11 at 11 25 45 am" src="https://user-images.githubusercontent.com/97163/32691285-3434ce86-c6d3-11e7-8033-54ec967061b8.png">

**Comment by ssetem** [comment]
nice @stereosteve 
We will think about how to integrate it, might require separate component.
We also need to think what does into Selected Filters, may a textual or visual indicator, not sure yet
