### ISSUE TITLE
Allow end user to use a query_string instead of just simple_query_string

### ISSUE THREAD

**Issue by drewdresser** [searchkit/searchkit#202]
**Use Case:**
To be able to include special syntax in the search box.
- A user is searching a catalog of products, a user could search "iphone -case" so that they could see iphones but NOT iphone cases.
- A user can search "+iphone 6" to indicate that the results MUST include "iphone" and the term "6" will only increase the relevency score.

**Current State:**
Searchkit uses simple_query_string by default, which is safer because users can put random costly regex and all, and the query is always valid.
Switching to query_string and sending an invalid query (like opening but not closing a parenthesis) will throw an error.

**Proposed Solution:**
Searchkit could have optional support for query_string and have it force searchOnChange to false.

**Relevent Links:**
- [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) 
- [Existing simple query string object](https://github.com/searchkit/searchkit/blob/f19fb8565dcc8e7b3d4d355908bb12fe93c13e8c/src/core/query/query_dsl/full_text/SimpleQueryString.ts)
- [The QueryAcessor that uses it](https://github.com/searchkit/searchkit/blob/c30b027db65564f67d4d9c57081d56a9b1ba5f0a/src/core/accessors/QueryAccessor.ts)

**Comment by joemcelroy** [comment]
Thanks for report. Yeh I tried switching to query string before release but due to issues with searchOnChange, I aborted on hoping new changes to Elasticsearch would improve error handling for query string. 

We will definitely look into being able to specify your own query parser, not just only query string / simple query, but any of the supported ES query parsers. For example, you can pass in your own function which  returns an ES query.

**Comment by joemcelroy** [comment]
this is done in #207. Should be ready for release for 0.9 and scheduled for release in next couple of days!
