### ISSUE TITLE
react-router + searchkit DOM Issue

### ISSUE THREAD

**Issue by alex-fernandez** [searchkit/searchkit#217]
Had anyone encountered this error, when doing a refresh on searchkit?

 error given was: Invariant Violation: Browser history needs a DOM

**Comment by GregoryPotdevin** [comment]
I think I had this error server side. Are you having it on the client ?

**Comment by alex-fernandez** [comment]
I am using it with React Redux Universal, the issue happens when the component is inside the react route component.

**Comment by joemcelroy** [comment]
Thanks for report. We are investigating using searchkit in a universal app. Tracking this in #4

**Comment by haovn577** [comment]
@alex-fernandez  Check page app was loaded before rendering SearchKit, maybe `componentDidMount`, a trick to bypass this issues.

**Comment by alex-fernandez** [comment]
@haovn577  Can you show me the code, I am adding the searchcomponent on the constructor

**Comment by coryalder** [comment]
I'm also trying to get server side rendering working and getting this same error. I would love some clarification about what the workaround for this is.

My render function looks like so:

    return <div id="searchblock">
      <SearchkitProvider searchkit={sk}>
        <div className="search">
          <div className="search__query">
            <SearchBox searchOnChange={true} />
          </div>
          <div className="search_results">
            <Hits hitsPerPage={20} itemComponent={Package} />
          </div>
        </div>
      </SearchkitProvider>
    </div>

Do I need to conditionally render the SearchkitProvider only if the page has loaded? or do I need to do something different with creating my searchkit object (sk)?

**Comment by thomasmodeneis** [comment]
Hi,

I'm also facing same issues for server side rendering, so far it seems that `SearchkitProvider.componentWillMount` at `/SearchkitProvider.js:15:30` is making use of DOM, witch conflicts with the react-router History Singletons:
` For React Components, this means using them only in lifecycle functions like componentDidMount, but not in componentWillMount.`
https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md

Is there any other ticket where this issue is being tracked ? any other references for this would be helpful.

Thanks
