### ISSUE TITLE
Multiple OR RefinementListFilters produces weird behavior

### ISSUE THREAD

**Issue by drewry** [searchkit/searchkit#261]
![options](https://cloud.githubusercontent.com/assets/427833/14961676/cd18361a-1068-11e6-87c0-da8d7e350da8.png)

When you select multiple options in an OR `RefinementListFilter` and then select one from another group, you can end up in a weird state as shown in the above screenshot.  You can go to [http://demo.fittery.com/twillory/](http://demo.fittery.com/twillory/) and pass in `colors[0]=Red&patterns[0]=Stripe` for an even weirder state where you can get stuck -- only way to get out of the filter combo is to hit back or refresh the page.

The code in question for reference:

```
<LayoutBody>
  <SideBar>
    <RefinementListFilter id="colors" title="Colors" field="colors.raw" operator="OR"/>
    <RefinementListFilter id="patterns" title="Patterns" field="patterns.raw" operator="OR"/>
    <RefinementListFilter id="cuffs" title="Cuffs" field="custom_filters_a.raw" operator="OR"/>
    <RefinementListFilter id="collars" title="Collars" field="custom_filters_b.raw" operator="OR"/>
  </SideBar>
  <LayoutResults>
    <Hits mod="sk-hits-grid" hitsPerPage={100} itemComponent={ItemHit}/>
    <NoHits/>
  </LayoutResults>
</LayoutBody>
```

**Comment by joemcelroy** [comment]
Thanks, we will have a look

**Comment by joemcelroy** [comment]
The weird state that you are mentioning is that it doesn't show some filters which were previously selected when another filter is removed / added from another group?

Whats happening is when you're selecting Red, the search expands from Checked OR Striped to RED AND (Checked Or Striped). there isnt a shirt which is Red AND Striped and therefore not brought back by ES as an aggregation. We display only the elastic aggregations. This may not include selected options, in this case.

We will probably improve the experience by always showing the selected filters, regardless if brought back by ES.

**Comment by drewry** [comment]
That's correct. I agree that having an option to always include selected filters in the results would be great. Thanks!

**Comment by GregoryPotdevin** [comment]
@joemcelroy It's pretty easy to re-inject the missing values in the accessor's `getBuckets` method

I'd like to point out, though, that we'll be hitting a limit in terms of performance. We already have 1 component which dynamically transforms the returned buckets, and that's MenuFilter (to add the "all" entry). The limit is that each time render is called it generates a new bucket and breaks the lazy re-rendering as the props aren't shallowly equal anymore even if the data hasn't changed. 
Injecting the missing value will have exactly the same issue.

I think the correct solution to this problem is to stop using the ES response as is and give the accessors the opportunity to update part of it when it is received. The same why the query is partially built with buildSharedQuery, when the response is received it could be passed to all accessors for transformations (like `accessor.mapQueryResults` ?). This could be the time to inject the "all" entry and missing values. 
SearchkitManager could keep a `rawResults` value to be able to re-run the map logic in case accessor options are changed (like having a `showAll` prop on `MenuFilter`). 

This could also be used for infinite scrolling, by just letting an InfinitePaginator load more results and append to the query results (and let React refresh the whole list). Not good enough for cache management and random page access but that would require management the hits independently from the queryResults.

@joemcelroy I'll try to post 2 PRs, one with a quick fix in the accessor that could be released as 0.9.4 and one to experiment with the query resulting mapping.

**Comment by joemcelroy** [comment]
yep. Its not urgent however. I think a few things come out of this:

- @drewry SelectedFilters component would be useful to add to your page. This will allow the user to reset their selections. SelectedFilters component does not rely on ES aggregations.

- On the no results state text, we should show the selected filters. For example displaying "No results for "test" with <Filter1> <Filter2>" and the filter style looking like selected filters. We implement a few renderer components for this like listComponent (one with just text, one with text and actionable filters)

- Yep what i was thinking the accessor is manipulating the options before passed to the component.

**Comment by drewry** [comment]
Ah SelectedFilters are a great idea! That will serve as an immediate improvement to the current experience. Thank you!

**Comment by drewry** [comment]
Hey guys, for anyone looking at this thread for a quick fix.  Here is a quick and very __dirty__ fix to just get it working with re-injecting the selected elements.

```javascript
// Wrap RefinementListFilter in a custom class
export class MyRefinementListFilter extends RefinementListFilter {
  getItems() {
    var buckets  = this.accessor.getBuckets();     // [{ doc_count: 3, key: "Black" }, { doc_count: 5, key: "Blue" }]
    var selected = this.accessor.state.getValue(); // ["Black", "Blue"]
    var filtered = [];

    // Add everything except for the selected values to our filtered array, we will re-inject these later
    // We can't know for certain if they will appear in the aggs so let's not have a condition where they appear twice
    buckets.map(function (item) {
      if (selected.indexOf(item.key) < 0) {
        filtered.push(item);
      }
    });

    // Map the selected to match the buckets and combine them
    var combined = filtered.concat(selected.map(function (selected) {
      return {
        doc_count: 0,
        key: selected
      }
    }));
    
    // Sort them alphabetically from A-Z
    // To sort by doc_count just change key to doc_count
    var sorted = combined.sort(function(a, b) {
      var keyA = a.key,
          keyB = b.key;

      // Compare the 2 letters
      if(keyA < keyB) return -1;
      if(keyA > keyB) return 1;
      return 0;
    })

    // Return the sorted
    return sorted
  }
}
```

**Comment by ssetem** [comment]
@drewry  we did a prerelease 0.10.0-5 with a fix for this

would you mind trying it out when you have a moment?

Thanks!

**Comment by Jaikant** [comment]
I am seeing the same behaviour, where the filters show only if there are available results to search within. If the filter is not applicable to the existing search results, the filter is not displayed. I think an option to yet display the filters would be great.
