### ISSUE TITLE
Custom history

### ISSUE THREAD

**Issue by mcs07** [searchkit/searchkit#297]
Would it be possible to allow a custom history object to be passed as a prop to `SearchkitManager`? I think this would be useful allow integration with things like react-router-redux.

**Comment by ssetem** [comment]
@mcs07 yeh, we currently have private createHistory() function we could use specified one and default to existing functionality PR maybe?:D

**Comment by xinghengwang** [comment]
that would be awesome! I noticed that any `<Link to='/search?userIdFilter=name'>`  in searchkit doesn't work. I believe it is due to history.  The use scenario would seem pretty common. Say the search lists produces a lot of widgets owned by different users. I would like to click on one of those users, and then immediately filter down to all the widget for that specific user. 
I noticed that if I do a `<Link to='/search?userIdFilter=name'>` anywhere outside of the searchkit, the link would work. (I am using react-router and react-router-redux), but if the link tag is generated within the search results, then it wouldn't work.

**Comment by xinghengwang** [comment]
Ok, I started working on it. 

However, I run into several issues. Since I am not too familiar with some of the internal working ehre. I was wondering if anyone here on here can give me a tip. 

I see in SearchKitManager that you call `createHistory()` when calling `setupListeners()`
Also, I see you customize the createHistory with the usesQuery function. According to the documentation of react router, the browserhistory object already set up for usesQuery.  So I should be able to just pass in the browserHistory that I used. 

I decided to use the options to pass in the history object. 
I made these changes, first here: 

```
export interface SearchkitOptions {
  useHistory?:boolean,
  searchOnLoad?:boolean,
  httpHeaders?:Object,
  basicAuth?:string,
  transport?:ESTransport,
  searchUrlPath?:string,
  history?:Object
}
```
then, in the setup Listeners(), where you had createHistory I had this. 

```
  setupListeners() {
    this.initialLoading = true
    if(this.options.useHistory) {
      this.unlistenHistory()
      if (this.options.history) {
          this.history = this.options.history;
      } else {
          this.history = createHistory()
      }
      this.listenToHistory()
    } else {
      this.runInitialSearch()
    }
  }
```

However, in the callback of history.listen()

the location parameter passed in is null, thus location.action fails here on the line where `location.action === "POP"` below: 

```
  listenToHistory(){
    let callsBeforeListen = (this.options.searchOnLoad) ? 1: 2

    this._unlistenHistory = this.history.listen(after(callsBeforeListen,(location)=>{
      //action is POP when the browser modified
      if(location.action === "POP") {
        this.registrationCompleted.then(()=>{
            this.searchFromUrlQuery(location.query)
        }).catch((e)=> {
          console.error(e.stack)
        })
      }
    }))
  }
```
However, when I make sure to catch the null, seems in the future, it works correctly. 

```
      if(location && location.action === "POP") {
        this.registrationCompleted.then(()=>{
            this.searchFromUrlQuery(location.query)
        }).catch((e)=> {
          console.error(e.stack)
        })
```
Does anyone know what I might be doing wrong? 

thanks,

**Comment by SickSAMA** [comment]
Allowing custom history object is not simple, a lot of scenarios need to be considered.

Suppose we have page A, B(Searchkit), C. They are in a single page app.

1. If a history is created in A, and user use a link navigate to B. Then searchkit's listener is not triggered because the location.action is ```PUSH```. Only when a history's first generated location or browser's ```popstate``` event generated location has a ```POP``` state. 

2. Normally when navigating from B to C, B will unmount. However, if C is a popup which is quite common (Instagram, Behance), So from B to C it can be a ```PUSH``` or ```POP```(use browser's forward button). If it's a ```POP```, then the listener is triggered a new search is done, which shouldn't happen. 

To solve above issues, I propose that search is triggered and only triggered by history's event and providing a ```pauseListenHistory``` and ```resumeListenHistory``` to disable the listener if on other pages.

```javascript
setupListeners() {
  this.initialLoading = true
  if(this.options.useHistory) {
    this.unlistenHistory()
    this.history = this.options.history || createHistory()
    this.historyFreezed = false; // indicate whether history is paused for listening
    this.listenToHistory()
  } else {
    this.runInitialSearch()
  }
}

listenToHistory(){
  let callsBeforeListen = (this.options.searchOnLoad) ? 1: 2
  this._unlistenHistory = this.history.listen(after(callsBeforeListen,(location)=>{
    if(!this.historyFreezed) { // only triggered when not freezed
      this.registrationCompleted.then(()=>{
        this.searchFromUrlQuery(location.query)
      }).catch((e)=> {
        console.error(e.stack)
      })
    }
  }))
}

performSearch(replaceState=false, notifyState=true){
  if(notifyState && !isEqual(this.accessors.getState(), this.state)){
    this.accessors.notifyStateChange(this.state)
  }
  this.state = this.accessors.getState(); // moved from _search to here
  if(this.options.useHistory){
    const historyMethod = (replaceState) ?
      this.history.replace : this.history.push
    historyMethod({pathname: window.location.pathname, query:this.state})
  }
  else {
    this._search()
  }
}

pauseListenHistory(){
  if (this.historyFreezed !== undefined) 
    this.historyFreezed = true
}

resumeListenHistory(){
  if (this.historyFreezed !== undefined) 
    this.historyFreezed = false
}
```

**Comment by abousamra** [comment]
I came across this issue while I was trying to listen to any URL changes by the filters and did this workaround to get it working 

```
    const history = createBrowserHistory();
    history.listen((location, action) => {
      // location is an object like window.location
    });

    const createHistory = () => history;
    this.sk = new Searchkit.SearchkitManager(".....", {
      createHistory,
    });
```

**Comment by ssetem** [comment]
yep @abousamra we upgraded and added hook to provide own history in v2.1

Thanks, I will close this issue down now
