### ISSUE TITLE
Uncaught Invariant Violation: 2 versions of react ?

### ISSUE THREAD

**Issue by sieutruc** [searchkit/searchkit#301]
Hello,

The search works fine, but i got a problem because your package uses another version of react. 

My current version is 

```
 "react": "^15.1.0",
"react-dom": "^15.1.0",
```

"Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)."

Do you know how to fix that error ?

**Comment by ssetem** [comment]
need to use webpack alias

https://github.com/searchkit/searchkit/issues/286

**Comment by tiemevanveen** [comment]
Yeah that works for me.

**Comment by sieutruc** [comment]
@tiemevanveen can you post your configuration using witth webpack pls ?

**Comment by tiemevanveen** [comment]
Something like this: 

```
module.exports = {
  
  // Other config here
  
  resolve: {
    alias: { react: path.resolve('./node_modules/react') },
    extensions: ['', '.js', '.jsx', '.json']
  }
};
```

**Comment by irnc** [comment]
This issue manifests itself when **app** uses React version different from one used by `searchkit`, which causes context for `ref` to be persisted in `ReactCurrentOwner.current` where `ReactCurrentOwner` instance is internal to `searchkit`. While external React couldn't see it and thus couldn't get owner to assign ref to.

Why do we need `ref="queryField"` on an input inside `SearchBox`? I couldn't find where it is used. Given that use case is clear, we could refactor `ref` to use new API, instead of legacy string API.

If we could change that `ref` to be a function [instead of string](https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs), that error would be gone.

Previously it was mitigated by webpack alias in https://github.com/searchkit/searchkit/issues/347 which works because then there is just _one_ instance of `ReactCurrentOwner` module in cache, but it is a workaround over a legacy usage, so better we change ref to be `input => this.refs.queryField = input` or `input => this.queryField = input` depending on interface, which I am unaware of.

**Comment by ssetem** [comment]
this should be already fixed in 2.x
