### ISSUE TITLE
react@15.3.2 issue

### ISSUE THREAD

**Issue by aquaristar** [searchkit/searchkit#346]
Hi, I am using django-react-redux seed and material-ui for web project.

I'd like to ship this searchkit to my project.

But searchkit is not working with react@15.x.x.

It require now react@14.8 but my all code use react@15.3.2

How can I resolve this issue?

**Comment by ssetem** [comment]
if you are using webpack, you can alias react so searchkit will use the aliased version

**Comment by aquaristar** [comment]
Can you please explain more detail? I am using now webpack.

**Comment by fabarea** [comment]
I faced this problem as well and could resolved it by adding into my webpack config file the lines bellow. To my understanding, it tells webpack to load only the first encountered react version and be "satisfied" with it - instead of loading multiple versions per package requirements e.g  searchkit requires a react 0.14.

```
	resolve: {
		...
		alias: {
			react: path.resolve('./node_modules/react')
		}
	},
```

**Comment by joemcelroy** [comment]
Closing this issue as the beta now has react 15 as a peerDependency. There is an issue with multiple copies of react being included and the temp fix for now is what @fabarea has mentioned.
