### ISSUE TITLE
Grouping Checkbox Filter

### ISSUE THREAD

**Issue by vanzi6** [searchkit/searchkit#388]
I am trying to write some code using documentation [link](http://docs.searchkit.co/stable/docs/components/navigation/checkbox-filter.html).
My goal is to make a filter using multiple check boxes.
This is simple code based on the documentation:

```
                    <CheckboxFilter id="Small" title="Small" label="Small" filter={
                    BoolMust([
                    RangeQuery("exifimagewidth", {lt: 1500})
                    ]) } />

                  <CheckboxFilter id="Big" title="Big" label="Big" filter={
                   BoolMust([
                   RangeQuery("exifimagewidth", {gt: 1501})
                   ])} />
```

![test](https://cloud.githubusercontent.com/assets/21037158/22826520/e6b23f24-efa3-11e6-8ec0-76046b357a67.jpg)

Is there any way to group this two check boxes together?
Something like title = Size and label1 = Small , label2 = Big?

**Comment by GregoryPotdevin** [comment]
I don't have the code to check, but all the filter components have a `containerComponent` (or something like that) prop to change the container (which displays the title and contents). So you could pass a different containerComponent that would just render the inner checkbox, and put both checkboxes in a container yourself. 

That won't work well though, because your users will be able to check both checkboxes and get 0 results. What you're trying to achieve looks like the NumericRefinementList : http://docs.searchkit.co/stable/docs/components/navigation/numeric-refinement-list.html
![image](https://cloud.githubusercontent.com/assets/1522455/22849014/651553ec-eff9-11e6-8829-73dd9188d718.png)

**Comment by vanzi6** [comment]
NumericRefinementList works just fine. So simple. Thank you so much. 

I see that [Selected Filters](http://docs.searchkit.co/stable/docs/components/navigation/selected-filters.html) has an override exapmle. It would be nice to have a small example in the [Checkbox Filter](http://docs.searchkit.co/stable/docs/components/navigation/checkbox-filter.html) section too.
