### ISSUE TITLE
Infinite Scroll for Hits Component

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#39]
- InfiniteScroll Accessor for hits

**Comment by jpeyper** [comment]
Can I give a +1 to this feature?

**Comment by bvaughn** [comment]
If there's interest in an integration with [react-virtualized](https://github.com/bvaughn/react-virtualized/), I'd be willing to help.

**Comment by GregoryPotdevin** [comment]
Thanks @bvaughn. This is more of an internal state management problem for now. We'll probably add support for multiple components when it lands and react-virtualized could be one of them.

**Comment by bvaughn** [comment]
Sounds great. Very nice library by the way. Saw it on Reddit earlier today and I'm impressed. :)

Please feel free to ping me once support is in place if you'd like a hand integrating with RV.

**Comment by GregoryPotdevin** [comment]
WIP implementation : https://github.com/searchkit/searchkit/compare/infinite-scrolling

Changes : 
- add "context" to SearchRequest. It's just `{ isMore: boolean }` for now. Used to bring more info to onResults/onError to treat some requests differently. Note that SearchRequest references SearchkitManager directly but it would be better if it just required an abstract SearchRequestResults (with onResults/onError)
- SearchkitManager.performShowMore(). Sets the context to `showMore: true`, removes the aggregators from the query (not a huge fan of having the manager change the query...), and when the results arrives merges the hits with the previous ones and keeps the original result (with the aggregators and all)
- InfiniteScrollingAccessor, forked from PaginationAccessor. It's actually the same for now but will need to be updated to prevent its state from being serialized in the url (not sure how to do that while keeping the page reset hack)
- InfiniteScrollingPagination, uses the accessor and calls `this.searchkit.performShowMore();` instead of `this.searchkit.performSearch()`. It also uses a VisibilitySensor to track when the user has scrolled to the end of the page. This is cloned from react-visibility-sensor for now, will need to be updated and reworked (the code is short so I advise cloning with correct attribution and adapting to avoid an external dependency). It would be better to start preloading results a little bit BEFORE the VisibilitySensor becomes visible (like if it's distance to the bottom of the screen if less that 25% of the screen height, or something like that). 

Note that my initial tests didn't have the VisibilitySensor but used a "Show More" button. It's just a 1 line change in InfiniteScrollingPagination's render method (render a button instead of a sensor), so this could be either a prop or a subclassed "ShowMorePagination" component. 

This is more of a POC with a few hacks so we need to see if the changes needed in SearchkitManager go in the right direction. I initially wanted to release this as an external package but the changes in SearchRequest make it tough (SearchkitManager could be subclassed to provide the extra logic). Actually as SearchkitManager is creating the SearchRequest I guess it could still work using a subclass, it has to redefine _search anyways.

@ssetem how long would it take to release this branch as a test version on NPM for those who want to test ? (without merging into Core for now)

**Comment by GregoryPotdevin** [comment]
And of course it's missing proper error management :)

**Comment by infacq** [comment]
+1

**Comment by lokat** [comment]
+1

**Comment by SabeehY** [comment]
+1

**Comment by UVSimulation** [comment]
+1

**Comment by juan-fdz-hawa** [comment]
This sounds like a feature I could definitely use. How can I help?

**Comment by byjoh** [comment]
+1 any update on this?

**Comment by samdash** [comment]
+1 any update on this?

**Comment by likeleto** [comment]
Trying to merge infinite scroll brunch with actual develop brunch, and got this
`(13,44): error TS2322: Type 'Function' is not assignable to type 'EventHandler<MouseEvent<HTMLButtonElement>>'.
  Type 'Function' provides no match for the signature '(event: MouseEvent<HTMLButtonElement>): void'`
Would appreciate any help

**Comment by likeleto** [comment]
finally beat it, so to launch searchkit in infine scroll mode and merged with latest verson, and it seems that everything ok.
for ShowMoreButton.tsx I updated callback function (actually I don't know why, because I've never used React, just found some examples here https://stackoverflow.com/questions/42081549/typescript-react-event-types it is not the ideal solution, but it works
`import * as React from "react";
import { ShowMoreProps } from './ShowMoreProps'

export class ShowMoreButton extends React.Component<ShowMoreProps, {}> {
  onShowMore = (e: any): void => {
    this.props.onShowMore()
    e.preventDefault()
  }
  render(){
    const { onShowMore, hasMore, isLoading } = this.props
    if (!hasMore) return null
    return (
      <div className="sk-pagination-show-more">
        {isLoading
           ? <button className="sk-button" disabled={true}>Loading...</button>
           : <button className="sk-button" onClick={this.onShowMore}>Show More</button>
          }
      </div>
    );
  }
}`
And the most important part to fix getTotalPages() function in InfiniteScrollingPagination.tsx because there is an error in line 53       
`get(this.getResults(), "**.**hits.total", 1)`
 return everytime 1 
it must be
`get(this.getResults(), "hits.total", 1)`
visit http://localhost:4000/infinite-app for demo
To turn autoscroll, change boolean constant autoLoad to true in test/e2e/server/apps/infinite-app/index.tsx line 67

**Comment by lasseborly** [comment]
Hey @ssetem we are about to go ahead and develop (or adopt this) infinite scroll implementation for searchkit because it's on a customers roadmap.

Can we do anything to prevent a fork and get this feature implemented here? What's the necessary actions that needs to be done for this to get into searchkit?

**Comment by joemcelroy** [comment]
Could you create a PR, base off staging branch and Il review it! Thanks

**Comment by lasseborly** [comment]
Cool @joemcelroy! I'll do that. Won't be right now, but it's in the near future. :tada:

**Comment by Davnatomy** [comment]
any updates on this feature?

**Comment by Fluorz** [comment]
Any update ?

**Comment by YannickArmspach** [comment]
Yes, i'm looking for this feature too. Can we work on it ?

**Comment by Fluorz** [comment]
I found another solution.
Increase pagination accessor value when the user is scrolling the page.

**ComponentDidMount :** 

```
componentDidMount() {
    window.addEventListener('scroll', this.handleScroll);
}

handleScroll = () => {
    this.setState({scroll: window.scrollY})
}
```

**ComponentDidUpdate :** 

```
componentDidUpdate() {
    if (this.state.scroll > 3000) {
      let type_accessor = this.props.searchkit.getAccessorsByType(PageSizeAccessor)["0"]
      type_accessor.state = type_accessor.state.setValue(500)
      this.props.searchkit.performSearch()
    }
  }
```

If the user is under 3000px of scroll I set a new value on pagination accessor
