### ISSUE TITLE
Disable the disabling of filters when nothing is found

### ISSUE THREAD

**Issue by leroy0211** [searchkit/searchkit#447]
We have a use case where `Filters` must be kept displayed when there is nothing found. 
For example when using the `RangeFilter`, that one must never disappear. But has to be `greyed out` or something.

Maybe an option which can be passed to the `Accessor` to turn off the disabling of Filters?

**Comment by ssetem** [comment]
I think it might be done by css currently, so could be overridden

**Comment by leroy0211** [comment]
Yes, I have seen it's been done with CSS, but then all panels which are disabled won't disappear anymore. It's not just on a `RangeFilter`, or specific RangeFilters (or any other filters).

**Comment by joemcelroy** [comment]
This issue has come up a few times. What do you want to be displayed if there are no results? What about allowing components to have a `noResultsComponent` prop and will be used to display the empty state?

**Comment by TheDolo** [comment]
Mostly on topic here: I currently have a Google Maps React component inside of listComponent={ComponentWithGMaps}, the problem is that every time search kit has no results (using QueryString, so happens often), the map is destroyed.  

Once the query changes and any amount of results are found, the map has to reinit costing another API token.  I was gonna tackle this myself by modifying the core, but any suggestions would be great!

**Comment by ssetem** [comment]
@TheDolo is this using the RefinementList?

**Comment by ssetem** [comment]
But yeh I think we need to make this easier to control, and make consistent across all components which hide when no results, I will brainstorm :D

**Comment by TheDolo** [comment]
No usage of RefinementList yet! Mostly because the amount of fields (and each field has a large amount of enums) is huge in our application, so looking through a long filter list and clicking isn't too quick from a user perspective.  Using QueryString to give the search box the "filter" effect in the search box, which results in a ton of 0 matches because it's not prefixing fields (unless operators are used), but looking for exact matches, which is our use case.  Cheers!

**Comment by chrisfinch** [comment]
Hitting this issue myself now, extra functionality would be great - I have a UX request to display icons and signage when a filter is empty/disabled and am currently having to override and extend various filter components to get it to work. 

A `noResultsComponent` as @joemcelroy suggests would be perfect.

**Comment by chrisfinch** [comment]
For completeness and for anyone googling here's a slimmed down example of how I'm using inheritance to enable a 'No Results' version of the filter component:

```typescript
import React from 'react';
import { MenuFilter } from 'searchkit';

export class NoResultsMenuFilter extends MenuFilter {

	render () {
		if (this.accessor.getBuckets().length > 0) {
			return super.render();
		} else {
			return (
				<div>
					No Results!
				</div>
			);
		}
	}

}
```
