### ISSUE TITLE
rangeFormatter function not used in filter 

### ISSUE THREAD

**Issue by wangchuande** [searchkit/searchkit#469]
<img width="286" alt="screenshot 2017-06-13 15 59 49" src="https://user-images.githubusercontent.com/7115982/27072441-f190638e-5052-11e7-9b15-1a5bb8c7018d.png">
<img width="433" alt="screenshot 2017-06-13 15 59 53" src="https://user-images.githubusercontent.com/7115982/27072443-f29c5710-5052-11e7-837b-43106a0e66c8.png">

rangeFormatter function used in rangeFilter but not used in top filter

**Comment by voke** [comment]
I guess It's because `GroupedSelectedFilters` are reading it's values from the actual query and has no connection to the `RangeFilter` component nor it's options (rangeFormatter). Same goes for the `translations` option in other components.
<img width="237" alt="screen1" src="https://user-images.githubusercontent.com/53462/27189932-2f11a7a8-51f3-11e7-8d07-22f70eff7d9d.png">
<img width="145" alt="screen2" src="https://user-images.githubusercontent.com/53462/27189935-32cef742-51f3-11e7-8b46-2aed6a5cdd7d.png">

**Comment by ssetem** [comment]
Yep, i think we need to apply formatting to value so Selected Filters inherits,

We will investigate this

**Comment by ssetem** [comment]
@wangchuande @voke 

this should be fixed in beta version 2.3.0-0

thanks!
