### ISSUE TITLE
Create Elasticsearch query and not use the search component

### ISSUE THREAD

**Issue by charlieroth** [searchkit/searchkit#476]
Is there a way to construct a query with this library that I am then able to send to my backend. We would just rather not be directly querying our Elasticsearch. Any help?

**Comment by bcruddy** [comment]
You can override the [transport object](https://github.com/searchkit/searchkit/blob/develop/src/core/transport/AxiosESTransport.ts). I had to reformat the elastic search query to what our backend expected, then translate the result back to an elastic search response. If you can just proxy the request through without changing it that would be best your best bet and just plug in your proxy endpoint for `host` when instantiating `SearchkitManager`. Otherwise you'll have to do some query and response formatting gymnastics.

**Comment by joemcelroy** [comment]
Yeh, recommend everyone who uses this in production to build the auth filters and append to ES request on the backend.
