### ISSUE TITLE
Option to replace %20 by - in the url

### ISSUE THREAD

**Issue by rolele** [searchkit/searchkit#560]
Thank you for this project. Keep up the good work.

I would like to have the option to replace the %20 in the url by a -.
Is it possible to do that currently ? If not is that a feature you would like to add to this project ?

Cheers,

**Comment by rolele** [comment]
Of course this means that the searchbox to url translation replace the space by -
And inversely the url to search box replace the - by space.
I would like this for SEO reasons and so I ultimately will be using your ssr express example.

**Comment by ssetem** [comment]
hi @rolele, I can kind of see what you need, but %20 is standards based url encoding for spaces, so you are looking to decode "-" back into a space?

**Comment by zoomore** [comment]
@ssetem Yeah it could be good if the searchbox had an to format the url. Maybe a callback fonction that the user of the searchbox could define to transform the string before updating the url.
Also a callback fonction to format back the url to the searchbox itself.

The main reason is that url with %20 appearing in a google search might discourage a user from clicking on that url because it appears spammy.

**Comment by rolele** [comment]
Yep, exactly what I am thinking

**Comment by ssetem** [comment]
@rolele cool.
We can allow programmer to override decode/encode url functions in future release, which allows you to solve by code.

**Comment by rolele** [comment]
It might also impact you SEO all toghether because I try very hard to find an example of a website using %20 in his url but I could not find one (at least it does not appear on the first pages)

**Comment by ssetem** [comment]
I see, other users also wanted to reshape url from ?.... to /somefilter/somevalue 
which is quite related

**Comment by rolele** [comment]
awesome, looking forward for this feature.
Thank you for the good work and for sharing this repo.
Cheers

**Comment by Fluorz** [comment]
+1
