### ISSUE TITLE
Upgrading to 2.3 causes error in TagFilterConfig

### ISSUE THREAD

**Issue by probabble** [searchkit/searchkit#634]
Searchkit fails to detect my `<TagFilterConfig />` elements after upgrading to v2.3.0 and does not register the required accessors.

CONFIG: `<TagFilterConfig field="instructor_list_filter" id="instructor" operator="AND" title="Instructor" />`
FILTER: `<TagFilter key={i} field="instructor_list_filter" value={f} />`

ERROR: Missing accessor for instructor_list_filter in TagFilter, add TagFilterConfig if needed

SIDE NOTE:
the docs about how to properly set up `TagFilterConfig` and `TagFilter` seem to have some errors in the required props... http://docs.searchkit.co/v2.0.0/components/navigation/tag-filter.html

ALSO:
are there any release notes since v2 was released?

**Comment by inostia** [comment]
I think the issue is that `TagFilterConfig />` is not adding the accessor to the `searchkit` object in `2.3.0`. I was able to add it manually using the following code:

```
const searchkit = new SearchkitManager("/search/courses");

// ...

const facetOptions = {
  field: "instructor_list_filter",
  id: "instructor",
  operator: "AND",
  title: "Instructor",
  size: 1,
  loadAggregations: false
}
const instructorAccessor = new FacetAccessor("instructor_list_filter", facetOptions);
searchkit.addAccessor(instructorAccessor);
```

I don't know if the required props to `TagFilterConfig` changed and whether there is a discrepancy on the docs, but it looks like `field` is the prop to add.
