### ISSUE TITLE
Add function_score to the Query

### ISSUE THREAD

**Issue by Laurent-Corron** [searchkit/searchkit#704]
Hello!
I need some help.

I would like to be able to add a [function_score query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html) to influence the score from Elasticsearch with the publication_date of a product like so:

```
{
  "query": {
    "function_score": {
      "linear": {
        "publication_date": {
          "origin": "now",
          "offset": "15d",
          "scale": "10d",
          "decay": 0.2
        }
      }
    }
  }
}
```
There doesn't seem to be a way right now in Searchkit to do this?

I tried with addQuery:
```
this.sk.addDefaultQuery((query)=> {
  return query.addQuery(
    {
      "function_score": {
        "linear": {
          "publication_date": {
            "origin": "now",
            "offset": "15d",
            "scale": "10d",
            "decay": 0.2
          }
        }
      }
    }
  );
});
```

But when you do this, it adds it to "bool":{"must":} like so:

```
{
  "query": {
    "bool": {
      "must": [{
        "function_score": {
          "linear": {
            "publication_date": {
              "origin": "now",
              "offset": "15d",
              "scale": "10d",
              "decay": 0.2
            }
          }
        }
      }]
    }
  }
}
```
And the results from Elasticsearch doesn't seem to be changed with this function added.
Is there any way to add the function_score to its correct location that I don't know of? 

Any help would be appreciated :wink:!

**Comment by Fluorz** [comment]
Hi ! 

You can add it like this : 

```
let accessor = searchkit.addDefaultQuery((query) => {
        return query.addQuery(
          {
              "function_score": {
              "query": { "match_all": {} },
              "functions": [
                  {
                      "filter": { "match": { "show": true } },
                      "weight": 0
                  },
                  {
                      "filter": { "match": { "show": false} },
                      "weight": 70
                  }
              ],
              "max_boost": 1000,
              "score_mode": "sum",
              "boost_mode": "multiply",
              "min_score" : 0
            }
          }
        )
      }
```

**Comment by Laurent-Corron** [comment]
Hello and thank you for your response!
I will be testing this out when I have a little bit more time and update after my tests.

**Comment by lmignon** [comment]
@Fluorz Thank you for your comment and sorry for the late feedback...
Unfortunately the proposed solution doesn't work and we haven't found a proper solution into searchkit. Indeed when using a function_score, the query element must placed into the function_score element as shown into the following picture...
![image](https://user-images.githubusercontent.com/544090/71981384-977c3d00-3222-11ea-9210-8ef5f25c1ee5.png)

Since we we haven't found our path into the current API, our temporary solution has been to patch the code of [MultiMatchQuery.ts](https://github.com/searchkit/searchkit/blob/staging/packages/searchkit/src/core/query/query_dsl/full_text/MultiMatchQuery.ts) to hardcode our function_score into the query object used in our case.
![image](https://user-images.githubusercontent.com/544090/71981675-25582800-3223-11ea-80dc-279a73b1d685.png)

Regards,

lmignon
