### ISSUE TITLE
Question: using searchkit client-side components only

### ISSUE THREAD

**Issue by cyrilcros** [searchkit/searchkit#765]
Hi,
is it possible to reuse searchkit React components with a different backend than the one you provide? Can you plug in an arbitrary GraphQL API endpoint?
Thanks!

**Comment by joemcelroy** [comment]
You can but your API endpoint will need to implement the same schema as searchkit (see demo schema within API playground https://demo.searchkit.co/api/graphql) and it could in future change. 

Could you tell me more about your setup?

If the issue is around already having a graphQL API and you use Apollo Server then should be really easy to add Searchkit's resolvers. If its another GraphQL server implementation, it shouldn't take too long for Searchkit's resolvers to integrate (its on my list to look at other popular servers).

If your API endpoint isn't powered by node, consider proxying the node Searchkit GraphQL API through your backend. Searchkit GraphQL doesn't take long to get up and running.

Thanks!

**Comment by cyrilcros** [comment]
Thanks @joemcelroy. I have started a django backend / react frontend project, and I was planning to add a graphQL api via [Graphene and its integrations with Django](https://graphene-python.org/). It relies on Relay for the GraphQL server.
I was hoping I can use your search component for the frontend, assuming I can use Searchkit with Relay....

**Comment by joemcelroy** [comment]
hey @cyrilcros yeh slightly difficult! Only thing i can think of is looking into apollo federation with graphene (https://github.com/preply/graphene-federation) and node app. Means you'll be able to have a singular graphql that encompasses both Search API Schema powered by node and your App API schema powered by django. Might be a little overkill and not sure would allow you to use relay.

**Comment by cyrilcros** [comment]
@joemcelroy Thanks for your replies and your time, I will probably end up writing my own search ui for my use case. Your project does look good, maybe some other time...
