### ISSUE TITLE
How to force send a post guest without cache? daterange component  bug

### ISSUE THREAD

**Issue by HSUCHING** [searchkit/searchkit#972]
Issue1:
I find it cannot send "post request" when  I click "reset" button. Or  I find it will not send new request when i search a word which I have searched. I have see the doc, I find it is problem about apollo/client. **I want know how i can force send a post request with blank query and no cache, when I click the reset button.**

Issue2:
I find a bug. I click on  "DateRangeFacet" on "sidebar", for example, I click "endtime component" after I select "starttime component", then I cannot select "endtime component"

**Comment by joemcelroy** [comment]
hey @HSUCHING - 
issue1: apollo cache can be a little tricky. I did fix an issue with caching recently so if you haven't already, upgrade to r41 (https://github.com/searchkit/searchkit/releases/tag/v3.0.0-canary.41). Curious to understand why you need to force a similar request again? Are you updating the index between requests so the request needs to be different? 

Otherwise you can disable request caching in apollo by using the `fetchPolicy` param (https://www.apollographql.com/docs/react/api/react/hooks/#fetchpolicy) on useQuery hook:
https://github.com/searchkit/searchkit/blob/next/examples/next/components/products.jsx#L117

```   
  const { previousData, data = previousData, loading } = useQuery(query, { variables, fetchPolicy: "network-only" })
```

issue2: do you mean that once you have selected the starttime and endtime and a search is performed, when you try to change either one, Searchkit doesn't make a further request?

**Comment by HSUCHING** [comment]
issue1: Because I use highlight custom css, if I cannot force send request when  I click "reset", I will get old data with wrong highlight style.

issue2: I give a operation process: For example, your example url: https://demo.searchkit.co/type/all?size=10
①. in sidebar daterange region
②. click  starttime and select a date
③. **_then if you click endtime, you will find that you cannot select a date that you want, system will give a default date._**

**Comment by joemcelroy** [comment]
issue1: aah i understand the issue. How apollo cache works is by creating cache fragments using the id. The problem with this scenario is that the last query updates the cache (including any highlighting results) so even though theres no query, the result hit contains the last cache.

Easiest way to avoid this issue is not to add id in the GQL query

remove id https://github.com/searchkit/searchkit/blob/next/examples/next/components/index.jsx#L72.

otherwise the other option is to avoid cache via `fetchPolicy`

issue 2: will look into it thanks :)
